# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c43b6168c8c3d8db6b55ff0cf8aa544"
name = "baana kom"
application_url = "https://spot-television-rubber-chronicles.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "baanakom.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_customers,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://spot-television-rubber-chronicles.trycloudflare.com/auth/callback",
  "https://spot-television-rubber-chronicles.trycloudflare.com/auth/shopify/callback",
  "https://spot-television-rubber-chronicles.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
